baseURL = "http://example.org/"
languageCode = "en-us"
title = "Stroud Masters"
theme = "mainroad"
# sectionPagesMenu = "main"
[permalinks]
  posts = "/:year/:month/:title/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2
[[menu.main]]
  name = "Calendar"
  url = "/calendar/"
  weight = 3
[[menu.main]]
  identifier = "club-records"
  name = "Club Records"
  url = "/club-records/"
  weight = 4
[[menu.main]]
  name = "Contact Us"
  url = "/contact-us/"
  weight = 5
[[menu.main]]
  name = "Training"
  url = "/training"
  weight = 6
[[menu.main]]
  name = "Partners"
  url = "/partners/"
  weight = 7
[[menu.main]]
  name = "Facebook"
  url = "https://www.facebook.com/groups/1408505989448473/"
  weight = 8

[[menu.main]]
  parent = "club-records"
  identifier = "short-course"
  name = "Short Course"
  url = "/club-records/short-course-records"
  weight = 1
[[menu.main]]
  parent = "club-records"
  identifier = "long-course"
  name = "Long Course"
  url = "/club-records/long-course-records"
  weight = 2
[[menu.main]]
  parent = "club-records"
  identifier = "open-water"
  name = "Open Water"
  url = "/club-records/open-water-records"
  weight = 3

[[menu.main]]
  parent = "short-course"
  name = "Freestyle"
  url = "/club-records/short-course-records/freestyle-sc"
  weight = 1
