baseURL = "http://example.org/"
languageCode = "en-us"
title = "Stroud Masters"
theme = "ananke"
# sectionPagesMenu = "main"
[permalinks]
  posts = "/:year/:month/:title/"

[[menu.main]]
  name = "About"
  url = "/about"
[[menu.main]]
  name = "Calendar"
  url = "/calender/"
[[menu.main]]
  name = "Club Records"
  url = "/club_records/"
